import PricingCards from '@/components/PricingCards';
import H1 from '@/components/Typography/H1';
import H2 from '@/components/Typography/H2';
import { APP_NAME } from '@/constants';
import { setAppTitle } from '@/lib/utils';
import { Metadata } from 'next/types';
import CTA from './components/CTA';
import FAQ from './components/FAQ';
import ImageCarousel from './components/ImageCarousel';
import LandingPageWrapper from './components/LandingPageWrapper';

export const metadata: Metadata = {
	title: setAppTitle('Login'),
	description: 'Generated by create next app',
};

export default function page() {
	return (
		<>
			<section>
				<LandingPageWrapper>
					<H1>
						Generate <span className="text-primary">Beautiful</span> Images with{' '}
						<span className="text-primary">{APP_NAME}</span>
					</H1>
				</LandingPageWrapper>

				{/* Carusel */}
				<div className="flex flex-col gap-2 md:gap-4 lg:gap-6 mt-8">
					<ImageCarousel />
					<ImageCarousel direction="backward" />
				</div>
			</section>

			<LandingPageWrapper>
				<section className="mt-8 w-full flex flex-col gap-4 items-center justify-center">
					<CTA />
				</section>

				<section className="mt-24 w-full">
					<FAQ />
				</section>

				<section className="mt-24 w-full">
					<H2>Pricing</H2>

					<div className="flex flex-col md:flex-row gap-4 mt-6 w-full">
						<PricingCards />
					</div>
				</section>
			</LandingPageWrapper>
		</>
	);
}
