import { Button } from '@/components/ui/button';
import { getStripeCredentials, setAppTitle } from '@/lib/utils';
import Link from 'next/link';
import { Metadata } from 'next/types';
import Stripe from 'stripe';

export const metadata: Metadata = {
	title: setAppTitle('Thank You!'),
	description: 'Generated by create next app',
};

const stripe = new Stripe(getStripeCredentials().secret);

export default async function page({
	searchParams,
}: {
	searchParams: { [key: string]: string | string[] | undefined };
}) {
	const session = await stripe.checkout.sessions.retrieve(searchParams?.session_id as string);
	const parsedSripeSession = JSON.parse(JSON.stringify(session));

	return (
		<>
			<h1 className="scroll-m-20 text-4xl font-extrabold tracking-tight lg:text-5xl text-center">
				Thank You!
			</h1>

			<div className="flex flex-col items-center gap-4 mt-8">
				<p className="leading-7 text-center">
					{parsedSripeSession?.metadata?.credits} credits have been added to your account.
				</p>

				<Button asChild>
					<Link href="/dashboard">Dashboard</Link>
				</Button>
			</div>
		</>
	);
}
