'use client';

import { Button } from '@/components/ui/button';

const ImageCount = 12584;

const CTA = () => {
	return (
		<div className="flex flex-col items-center justify-center gap-4">
			<p className="text-lg sm:w-96 max-w-full text-center">
				Over <b>{ImageCount.toLocaleString()}+ images</b> generated by our users.
			</p>

			<Button>Get Started</Button>
		</div>
	);
};

export default CTA;
