import H1 from '@/components/Typography/H1';
import { setAppTitle } from '@/lib/utils';
import { Metadata } from 'next/types';
import LoginForm from './components/LoginForm';

export const metadata: Metadata = {
	title: setAppTitle('Login'),
	description: 'Generated by create next app',
};

export default function page() {
	return (
		<div className="flex flex-col w-full h-full md:my-auto items-center justify-center">
			<H1>Login to Your Account</H1>

			<LoginForm />
		</div>
	);
}
