import { Button } from '@/components/ui/button';
import { setAppTitle } from '@/lib/utils';
import Link from 'next/link';
import { Metadata } from 'next/types';

export const metadata: Metadata = {
	title: setAppTitle('Payment Cancelled'),
	description: 'Generated by create next app',
};

export default function page() {
	return (
		<>
			<h1 className="scroll-m-20 text-4xl font-extrabold tracking-tight lg:text-5xl text-center">
				Payment Cancelled
			</h1>

			<div className="flex flex-col items-center gap-4 mt-8">
				<p className="leading-7 text-center">The good news is, you can try again later.</p>

				<Button asChild>
					<Link href="/dashboard">Dashboard</Link>
				</Button>
			</div>
		</>
	);
}
