import H1 from '@/components/Typography/H1';
import { Button } from '@/components/ui/button';
import { setAppTitle } from '@/lib/utils';
import Link from 'next/link';
import { Metadata } from 'next/types';

export const metadata: Metadata = {
	title: setAppTitle('Payment Cancelled'),
	description: 'Generated by create next app',
};

export default function page() {
	return (
		<>
			<H1>Payment Cancelled</H1>

			<div className="flex flex-col items-center gap-4 mt-8">
				<p className="leading-7 text-center">The good news is, you can try again later.</p>

				<Button asChild>
					<Link href="/dashboard">Dashboard</Link>
				</Button>
			</div>
		</>
	);
}
