import PricingCards from '@/components/PricingCards';
import H1 from '@/components/Typography/H1';
import { setAppTitle } from '@/lib/utils';
import { Metadata } from 'next/types';

export const metadata: Metadata = {
	title: setAppTitle('Pricing'),
	description: 'Generated by create next app',
};

const page = () => {
	return (
		<>
			<H1>Pricing</H1>

			<div className="mt-8 flex flex-col md:flex-row gap-4 w-full">
				<PricingCards />
			</div>
		</>
	);
};

export default page;
