import PricingCards from '@/components/PricingCards';
import { setAppTitle } from '@/lib/utils';
import { Metadata } from 'next/types';

export const metadata: Metadata = {
	title: setAppTitle('Pricing'),
	description: 'Generated by create next app',
};

const page = () => {
	return (
		<>
			<h1 className="scroll-m-20 text-4xl font-extrabold tracking-tight lg:text-5xl text-center">
				Pricing
			</h1>

			<div className="mt-8 flex flex-col md:flex-row gap-4 w-full">
				<PricingCards />
			</div>
		</>
	);
};

export default page;
