import { setAppTitle } from '@/lib/utils';
import { Metadata } from 'next/types';
import Credits from './Credits';

export const metadata: Metadata = {
	title: setAppTitle('Dashboard'),
	description: 'Generated by create next app',
};

const page = () => {
	return (
		<>
			<h1 className="scroll-m-20 text-4xl font-extrabold tracking-tight lg:text-5xl text-center">
				Dashboard
			</h1>

			<Credits />
		</>
	);
};

export default page;
