import H1 from '@/components/Typography/H1';
import { setAppTitle } from '@/lib/utils';
import { Metadata } from 'next/types';
import Credits from './Credits';

export const metadata: Metadata = {
	title: setAppTitle('Dashboard'),
	description: 'Generated by create next app',
};

const page = () => {
	return (
		<>
			<H1>Dashboard</H1>

			<Credits />
		</>
	);
};

export default page;
