import { Button } from '@/components/ui/button';
import { setAppTitle } from '@/lib/utils';
import Link from 'next/link';
import { Metadata } from 'next/types';

export const metadata: Metadata = {
	title: setAppTitle('Dashboard'),
	description: 'Generated by create next app',
};

const page = () => {
	return (
		<>
			<h1 className="scroll-m-20 text-4xl font-extrabold tracking-tight lg:text-5xl text-center">
				Dashboard
			</h1>

			<div className="flex flex-col items-center gap-4 mt-8">
				<p>
					You have <span className="text-primary">0</span> credits remaining.
				</p>

				<Button asChild>
					<Link href="/pricing">Buy more credits</Link>
				</Button>
			</div>
		</>
	);
};

export default page;
